import { CONSTRAINTS, FEATURE_TYPES, PLANES, SKETCH_TOOLS, UNITS } from '../constants.js';
import { escapeHTML } from '../utils.js';
import { icon } from './icons.js';

export function welcomeTemplate(projects=[]){return`<main class="welcome-shell">
  <header class="welcome-brand"><img src="./assets/logo-mark.svg" alt=""><img class="wordmark" src="./assets/wordmark.svg" alt="FeatherCAD"><button class="icon-button theme-toggle" data-action="theme" aria-label="Toggle color theme">${icon('settings')}</button></header>
  <section class="welcome-card" aria-labelledby="welcome-title"><div class="welcome-copy"><span class="eyebrow">Sketch precisely. Build lightly.</span><h1 id="welcome-title">CAD shaped for your fingertips.</h1><p>Create constrained sketches and editable 3D features in a fast, private browser workspace.</p></div>
  <div class="welcome-actions"><button class="primary big" data-action="new-project">${icon('new','New Project')}</button><button class="secondary big" data-action="open-project">${icon('open','Open Project')}</button><button class="secondary big" data-action="import-project">${icon('import','Import File')}</button></div></section>
  ${projects.length?`<section class="recent" aria-labelledby="recent-title"><div class="section-heading"><h2 id="recent-title">Recent Projects</h2><span>${projects.length} saved locally</span></div><div class="recent-grid">${projects.slice(0,8).map(p=>`<button class="project-card" data-action="load-project" data-id="${p.id}"><span class="project-thumb">${icon('cube')}</span><span><strong>${escapeHTML(p.name)}</strong><small>${escapeHTML(p.units.toUpperCase())} · ${new Date(p.updatedAt).toLocaleDateString()}</small></span></button>`).join('')}</div></section>`:''}
  <footer>Local-first · No account required · Polygonal CAD engine</footer></main>`;}

export function workspaceTemplate(project){return`<main class="workspace" data-mode="model">
  <header class="topbar"><button class="brand-button" data-action="home" aria-label="Return to welcome"><img src="./assets/logo-mark.svg" alt=""></button><div class="project-title"><strong>${escapeHTML(project.name)}</strong><span class="save-state">Saved</span></div><div class="mode-pill" id="mode-pill">3D MODEL</div><div class="top-actions"><button class="icon-button" data-action="undo" aria-label="Undo">${icon('undo')}</button><button class="icon-button" data-action="redo" aria-label="Redo">${icon('redo')}</button><button class="icon-button desktop-only" data-action="save" aria-label="Save">${icon('save')}</button><button class="icon-button" data-action="project-menu" aria-label="Project menu">${icon('menu')}</button></div></header>
  <aside class="tree-panel" id="tree-panel"><div class="panel-title"><span>Model</span><button class="icon-button mobile-only" data-action="toggle-tree" aria-label="Close model tree">${icon('close')}</button></div><div id="feature-tree" class="feature-tree"></div></aside>
  <section class="viewport-shell" id="viewport-shell"><canvas id="viewport" aria-label="3D model viewport"></canvas><svg id="sketch-overlay" class="sketch-overlay" aria-label="2D sketch canvas"></svg><div class="viewport-hud"><div class="view-cluster"><button data-view="top">TOP</button><button data-view="front">FRONT</button><button data-view="right">RIGHT</button><button data-view="iso" class="active">ISO</button></div><button class="orientation-gem" data-action="orientation-menu" aria-label="View orientation">${icon('cube')}</button></div><div class="selection-hint" id="selection-hint">Select a plane to begin a sketch</div><div class="snap-badge" id="snap-badge" hidden></div><div class="progress" id="operation-progress" hidden><span></span><button data-action="cancel-operation">Cancel</button></div></section>
  <aside class="properties-panel" id="properties-panel"><div class="panel-title"><span>Properties</span><button class="icon-button mobile-only" data-action="close-properties" aria-label="Close properties">${icon('close')}</button></div><div id="properties-content" class="properties-content"><div class="empty-state">Select a plane, sketch, feature, or body to inspect it.</div></div></aside>
  <nav class="bottom-dock" aria-label="Primary tools"><button data-action="toggle-tree">${icon('tree','Model')}</button><button data-action="start-sketch">${icon('sketch','Sketch')}</button><button data-action="feature-menu">${icon('feature','Feature')}</button><button data-action="measure">${icon('measure','Measure')}</button><button data-action="view-menu">${icon('cube','View')}</button><button data-action="project-menu">${icon('more','More')}</button></nav>
  <div class="command-bar" id="command-bar" hidden><button class="cancel-command" data-action="cancel-command">${icon('close','Cancel')}</button><span id="command-instruction"></span><button class="confirm-command" data-action="confirm-command">${icon('check','Confirm')}</button></div>
  <div id="sheet-layer"></div><div id="dialog-layer"></div>
  </main>`;}

export function treeTemplate(project){const row=(item,kind,iconName='cube',extra='')=>`<button class="tree-row ${project.selectedId===item.id?'selected':''}" data-action="select-item" data-id="${item.id}" data-kind="${kind}">${icon(iconName)}<span>${escapeHTML(item.name)}</span>${extra}<i class="status-dot ${item.status||''}"></i></button>`;return`${row({id:'origin',name:'Origin'},'origin','fit')}
  <div class="tree-group"><h3>Planes</h3>${project.planes.map(p=>row(p,'plane','sketch',`<span class="visibility">${icon(p.visible?'eye':'hidden')}</span>`)).join('')}</div>
  ${project.sketches.length?`<div class="tree-group"><h3>Sketches</h3>${project.sketches.map(s=>row(s,'sketch','sketch',`<small>${s.status}</small>`)).join('')}</div>`:''}
  ${project.bodies.length?`<div class="tree-group"><h3>Bodies</h3>${project.bodies.map(b=>row(b,'body','cube')).join('')}</div>`:''}
  ${project.features.length?`<div class="tree-group"><h3>History</h3>${project.features.map(f=>row(f,'feature','feature',f.suppressed?'<small>suppressed</small>':'')).join('')}</div>`:''}
  ${project.imports.length?`<div class="tree-group"><h3>Imports</h3>${project.imports.map(i=>row(i,'import','import','<small>mesh</small>')).join('')}</div>`:''}`;}

export function newProjectDialog(){return dialog('New Project',`<form id="new-project-form"><label>Project name<input name="name" value="Untitled" required maxlength="80" autocomplete="off"></label><label>Measurement units<select name="units">${Object.entries(UNITS).map(([v,u])=>`<option value="${v}" ${v==='mm'?'selected':''}>${u.label}</option>`).join('')}</select></label><label>Template<select name="template"><option value="blank">Blank</option><option value="metric-product">Metric product (preferences only)</option><option value="imperial-product">Imperial product (preferences only)</option></select></label><p class="field-help">Templates configure units and preferences. They never add geometry.</p><div class="dialog-actions"><button type="button" class="secondary" data-action="close-dialog">Cancel</button><button class="primary" type="submit">Create Project</button></div></form>`);}
export function dialog(title,body){return`<div class="modal-backdrop" data-action="close-dialog"><section class="dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title" data-stop><header><h2 id="dialog-title">${escapeHTML(title)}</h2><button class="icon-button" data-action="close-dialog" aria-label="Close">${icon('close')}</button></header>${body}</section></div>`;}
export function sheet(title,body,{wide=false}={}){return`<div class="sheet-backdrop" data-action="close-sheet"><section class="bottom-sheet ${wide?'wide':''}" role="dialog" aria-modal="true" data-stop><div class="sheet-grabber"></div><header><h2>${escapeHTML(title)}</h2><button class="icon-button" data-action="close-sheet" aria-label="Close">${icon('close')}</button></header><div class="sheet-body">${body}</div></section></div>`;}
export function sketchToolsSheet(active){return sheet('Sketch tools',`<div class="tool-grid">${SKETCH_TOOLS.map(([id,label])=>`<button data-sketch-tool="${id}" class="${id===active?'active':''}"><span class="tool-glyph">${label.slice(0,2).toUpperCase()}</span><span>${label}</span></button>`).join('')}</div><button class="secondary full" data-action="constraint-menu">Constraints & dimensions</button>`,{wide:true});}
export function constraintsSheet(){return sheet('Constraints & dimensions',`<p class="field-help">Select geometry, then apply a relation. Dimensional relations open a value editor.</p><div class="tool-grid compact">${CONSTRAINTS.map(([id,label])=>`<button data-constraint="${id}"><span class="constraint-glyph">${label[0]}</span><span>${label}</span></button>`).join('')}</div>`,{wide:true});}
export function featuresSheet(){return sheet('Add feature',`<div class="feature-list">${FEATURE_TYPES.map(([id,label])=>`<button data-feature="${id}">${icon(id==='referencePlane'?'sketch':'feature')}<span><strong>${label}</strong><small>${featureHint(id)}</small></span></button>`).join('')}</div>`,{wide:true});}
function featureHint(id){return{extrude:'Raise a closed profile',cut:'Remove with a profile',revolve:'Rotate a profile about its Y axis',revolveCut:'Revolved removal',fillet:'Round the selected body globally',chamfer:'Bevel the selected body globally',shell:'Create a translucent wall preview',linearPattern:'Repeat along an axis',circularPattern:'Repeat around an axis',mirror:'Reflect across an origin plane',referencePlane:'Offset or angle a plane',boolean:'Union, subtract, or intersect two bodies'}[id]||'';}
export function viewSheet(renderer){return sheet('View & display',`<div class="segmented"><button data-projection="perspective" class="${renderer.camera.isPerspectiveCamera?'active':''}">Perspective</button><button data-projection="orthographic" class="${renderer.camera.isOrthographicCamera?'active':''}">Orthographic</button></div><h3>Orientation</h3><div class="view-grid">${['front','back','left','right','top','bottom','iso'].map(v=>`<button data-view="${v}">${v}</button>`).join('')}<button data-action="fit">Fit</button></div><h3>Display</h3><div class="segmented wrap">${['shaded','edges','wireframe','transparent'].map(v=>`<button data-display="${v}" class="${renderer.displayMode===v?'active':''}">${v}</button>`).join('')}</div><label class="switch"><input type="checkbox" data-visibility="grid" checked><span>Grid</span></label><label class="switch"><input type="checkbox" data-visibility="planes" checked><span>Reference planes</span></label><label class="switch"><input type="checkbox" data-visibility="axes" checked><span>Axes</span></label><label class="switch"><input type="checkbox" data-section><span>Section view</span></label><h3>Selection filter</h3><div class="segmented wrap">${['body','feature','face','edge','vertex'].map(v=>`<button data-filter="${v}" class="${renderer.selectionFilter===v?'active':''}">${v}</button>`).join('')}</div>`);}
export function projectMenu(){return sheet('Project',`<div class="menu-list"><button data-action="save">${icon('save')}Save</button><button data-action="save-as">${icon('save')}Save As</button><button data-action="rename-project">${icon('sketch')}Rename Project</button><button data-action="duplicate-project">${icon('new')}Duplicate Project</button><button data-action="import-project">${icon('import')}Import File</button><button data-action="export-menu">${icon('export')}Export</button><button data-action="new-project">${icon('new')}New Project</button><button data-action="home">${icon('open')}Welcome screen</button><button class="danger" data-action="delete-project">${icon('trash')}Delete Project</button></div>`);}
export function exportSheet(){return sheet('Export',`<form id="export-form"><label>Format<select name="format"><option value="feathercad">FeatherCAD native (.feathercad)</option><option value="stl">STL</option><option value="obj">OBJ</option><option value="glb">glTF Binary (.glb)</option><option value="gltf">glTF JSON (.gltf)</option><option value="svg">Sketch SVG</option><option value="dxf">Sketch DXF</option><option value="png">Viewport PNG</option></select></label><label>Scope<select name="scope"><option value="all">Entire project</option><option value="selected">Selected body</option></select></label><label class="switch"><input name="binary" type="checkbox" checked><span>Binary where applicable</span></label><label class="switch"><input name="includeHidden" type="checkbox"><span>Include hidden bodies</span></label><div class="warning-card">Mesh formats cannot preserve parametric history, constraints, or exact analytic surfaces.</div><button class="primary full" type="submit">Export file</button></form>`);}
export function gestureGuide(){return dialog('Move through 3D',`<div class="gesture-guide"><div><span>☝️</span><strong>Drag</strong><small>Orbit or draw</small></div><div><span>✌️</span><strong>Two-finger drag</strong><small>Pan</small></div><div><span>🤏</span><strong>Pinch</strong><small>Zoom</small></div><div><span>⏱️</span><strong>Long press</strong><small>Context actions</small></div></div><p>No sample geometry is added. Select a reference plane in the model tree, then tap Sketch.</p><button class="primary full" data-action="close-dialog">Got it</button>`);}
