import * as THREE from 'three';
import { AUTOSAVE_MS, UNITS } from './constants.js';
import { commands } from './commands.js';
import { projectDB } from './db.js';
import { CADRenderer } from './renderer.js';
import { createProject, store } from './store.js';
import { createSketch, detectProfiles, profilePoints } from './sketch/model.js';
import { SketchView } from './sketch/view.js';
import { SketchController } from './sketch/controller.js';
import { addConstraint, addDimension, inferredDimension, solveSketch } from './sketch/solver.js';
import { createFeature, planRebuild, syncBodies } from './history.js';
import { importer } from './io/importer.js';
import { exportProject } from './io/exporter.js';
import { clone, debounce, escapeHTML, fileBase, parseUnitValue, safeName, uid } from './utils.js';
import { propertiesTemplate } from './ui/properties.js';
import { constraintsSheet, dialog, exportSheet, featuresSheet, gestureGuide, newProjectDialog, projectMenu, sheet, sketchToolsSheet, treeTemplate, viewSheet, welcomeTemplate, workspaceTemplate } from './ui/templates.js';

class FeatherCADApp {
  constructor(root){
    this.root=root;this.renderer=null;this.sketchView=null;this.sketchController=null;this.mode='welcome';this.activeTool='select';this.confirmHandler=null;this.cancelHandler=null;this.sketchEntrySnapshot=null;
    this.autoSave=debounce(()=>this.save(true),AUTOSAVE_MS);this.lastBodyId=null;this.bind();this.install();this.showWelcome();
    store.addEventListener('change',()=>{this.refresh();this.autoSave();});store.addEventListener('selection',()=>this.refreshSelection());
    importer.addEventListener('progress',e=>this.progress(e.detail.progress));
    addEventListener('beforeunload',()=>{if(store.dirty&&store.project)projectDB.recovery.put(store.project).catch(()=>{});});
  }
  bind(){
    this.root.addEventListener('click',e=>this.click(e));this.root.addEventListener('submit',e=>this.submit(e));this.root.addEventListener('change',e=>this.change(e));this.root.addEventListener('keydown',e=>this.keydown(e));
    document.getElementById('file-picker').addEventListener('change',e=>this.importFile(e.target.files[0]));
    document.addEventListener('keydown',e=>this.globalKeys(e));
  }
  install(){if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./service-worker.js').catch(()=>{});this.applyTheme(localStorage.getItem('feathercad-theme')||'system');}
  async showWelcome(){this.mode='welcome';this.renderer?.destroy?.();this.renderer=null;store.project=null;const projects=await projectDB.list().catch(()=>[]);this.root.innerHTML=welcomeTemplate(projects);}
  async openWorkspace(project,{guide=false}={}){
    this.mode='model';store.setProject(project);this.root.innerHTML=workspaceTemplate(store.project);this.renderer=new CADRenderer(this.q('#viewport-shell'),this.q('#viewport'));this.renderer.setProject(store.project);this.renderer.addEventListener('selection',e=>{const id=e.detail.featureId||e.detail.id;store.select(id);});this.renderer.addEventListener('rebuilt',()=>{syncBodies(store.project);this.refresh();});
    this.sketchView=new SketchView(this.q('#sketch-overlay'));this.sketchController=new SketchController(this.sketchView,store);this.sketchController.addEventListener('error',e=>this.toast(e.detail.message,'error'));this.sketchController.addEventListener('tool',e=>this.setInstruction(e.detail.tool));this.sketchController.addEventListener('dimension',e=>this.editDimension(e.detail.id));this.sketchController.addEventListener('project',()=>this.projectExternal());
    this.attachLongPress();this.refresh();if(project.camera?.projection==='orthographic')this.renderer.setProjection('orthographic');if(guide)this.openDialog(gestureGuide());
  }
  click(event){
    const target=event.target.closest('button,[data-action],[data-view],[data-sketch-tool],[data-constraint],[data-feature],[data-display],[data-projection],[data-filter]');if(!target)return;if(target.closest('[data-stop]')&&target===event.target.closest('[data-action="close-dialog"],[data-action="close-sheet"]')&&target.dataset.stop!==undefined)return;
    const action=target.dataset.action;if(action){event.preventDefault();this.action(action,target,event);return;}
    if(target.dataset.view){this.renderer?.setView(target.dataset.view);this.closeSheet();}
    if(target.dataset.sketchTool){this.activeTool=target.dataset.sketchTool;this.sketchController.setTool(this.activeTool);this.closeSheet();this.setInstruction(this.activeTool);}
    if(target.dataset.constraint){this.applyConstraint(target.dataset.constraint);}
    if(target.dataset.feature){this.configureFeature(target.dataset.feature);}
    if(target.dataset.display){this.renderer.setDisplay(target.dataset.display);this.openSheet(viewSheet(this.renderer));}
    if(target.dataset.projection){this.renderer.setProjection(target.dataset.projection);this.openSheet(viewSheet(this.renderer));}
    if(target.dataset.filter){this.renderer.setSelectionFilter(target.dataset.filter);this.openSheet(viewSheet(this.renderer));}
  }
  async action(action,target,event){
    const actions={
      'new-project':()=>this.openDialog(newProjectDialog()),'open-project':()=>this.openProjectPicker(),'import-project':()=>document.getElementById('file-picker').click(),'load-project':()=>this.loadProject(target.dataset.id),
      'home':()=>this.goHome(),'theme':()=>this.toggleTheme(),'toggle-tree':()=>this.q('#tree-panel')?.classList.toggle('open'),'close-properties':()=>this.q('#properties-panel')?.classList.remove('open'),
      'select-item':()=>this.selectItem(target.dataset.id,target.dataset.kind),'start-sketch':()=>store.project?.activeSketchId?this.openSheet(sketchToolsSheet(this.activeTool)):this.startSketch(),'edit-sketch':()=>this.enterSketch(target.dataset.id),
      'undo':()=>{if(store.undo())this.renderer?.rebuild();},'redo':()=>{if(store.redo())this.renderer?.rebuild();},'save':()=>this.save(false),'save-as':()=>this.saveAs(),'rename-project':()=>this.renameProject(),'duplicate-project':()=>this.duplicateProject(),'delete-project':()=>this.deleteProject(),
      'project-menu':()=>this.openSheet(projectMenu()),'feature-menu':()=>this.openSheet(featuresSheet()),'constraint-menu':()=>this.openSheet(constraintsSheet()),'view-menu':()=>this.openSheet(viewSheet(this.renderer)),'orientation-menu':()=>this.openSheet(viewSheet(this.renderer)),
      'fit':()=>{this.renderer.fit(this.renderer.selected);this.closeSheet();},'measure':()=>this.measure(),'export-menu':()=>this.openSheet(exportSheet()),'close-sheet':()=>this.closeSheet(),'close-dialog':()=>this.closeDialog(),
      'confirm-command':()=>this.confirmCommand(),'cancel-command':()=>this.cancelCommand(),'cancel-operation':()=>{importer.cancel();this.progress(null);},'delete-item':()=>this.deleteSelected(),'move-feature-up':()=>this.moveFeature(-1),'move-feature-down':()=>this.moveFeature(1)
    };await actions[action]?.();
  }
  submit(event){event.preventDefault();if(event.target.id==='new-project-form'){const data=Object.fromEntries(new FormData(event.target));if(data.template==='imperial-product')data.units='in';else if(data.template==='metric-product')data.units='mm';const project=createProject(data);this.closeDialog();this.openWorkspace(project,{guide:!localStorage.getItem('feathercad-guided')});localStorage.setItem('feathercad-guided','1');this.save(true);}
    if(event.target.id==='feature-form')this.createConfiguredFeature(new FormData(event.target));
    if(event.target.id==='export-form'){const data=Object.fromEntries(new FormData(event.target));this.closeSheet();exportProject({format:data.format,project:store.project,renderer:this.renderer,scope:data.scope,binary:!!data.binary,includeHidden:!!data.includeHidden}).then(()=>this.toast('Export ready.')).catch(e=>this.toast(e.message,'error'));}
    if(event.target.id==='value-form'){const value=Number(new FormData(event.target).get('value'));this.confirmHandler?.(value);this.confirmHandler=null;this.closeDialog();}
    if(event.target.id==='rename-form'){const value=String(new FormData(event.target).get('name')).trim();this.confirmHandler?.(value);this.confirmHandler=null;this.closeDialog();}
  }
  change(event){const t=event.target;if(t.dataset.visibility){store.mutate('Change viewport visibility',p=>p.visibility[t.dataset.visibility]=t.checked);this.renderer.updateReferences();return;}if(t.dataset.section!==undefined){this.renderer.toggleSection(t.checked);return;}if(!t.dataset.property)return;const id=store.project.selectedId,key=t.dataset.property,value=t.type==='checkbox'?t.checked:(t.type==='number'?Number(t.value):t.value);store.mutate('Edit properties',project=>{let item;for(const group of ['planes','sketches','features','bodies','imports']){item=project[group].find(x=>x.id===id);if(item)break;}if(!item)return;if(key.startsWith('param.'))item.params[key.slice(6)]=value;else item[key]=value;});if(key==='visible')this.renderer.setVisibility(id,value);else this.renderer.rebuild();}
  keydown(event){if(event.key==='Escape'){this.closeSheet();this.closeDialog();}}
  globalKeys(event){if(this.mode==='welcome'||/INPUT|SELECT|TEXTAREA/.test(event.target.tagName))return;const cmd=event.metaKey||event.ctrlKey;if(cmd&&event.key.toLowerCase()==='z'){event.preventDefault();event.shiftKey?store.redo():store.undo();this.renderer?.rebuild();}if(cmd&&event.key.toLowerCase()==='s'){event.preventDefault();this.save(false);}if(event.key==='Delete'||event.key==='Backspace'){if(store.project?.selectedId)this.deleteSelected();}if(event.key==='Escape'&&store.project?.activeSketchId)this.sketchController.cancel();if(event.key.toLowerCase()==='f')this.renderer?.fit(this.renderer.selected);}
  refresh(){if(this.mode==='welcome'||!store.project)return;const tree=this.q('#feature-tree');if(tree)tree.innerHTML=treeTemplate(store.project);this.refreshSelection();const save=this.q('.save-state');if(save)save.textContent=store.dirty?'Unsaved':'Saved';this.q('.project-title strong').textContent=store.project.name;}
  refreshSelection(){if(this.mode==='welcome'||!store.project)return;const content=this.q('#properties-content');if(content)content.innerHTML=propertiesTemplate(store.project,store.project.selectedId);for(const row of this.root.querySelectorAll('.tree-row'))row.classList.toggle('selected',row.dataset.id===store.project.selectedId);if(innerWidth<900&&store.project.selectedId)this.q('#properties-panel')?.classList.add('open');}
  selectItem(id,kind){store.select(id);if(kind==='body')this.lastBodyId=id;if(kind==='body'||kind==='plane')this.renderer.select(this.renderer.findById(id));this.q('#tree-panel')?.classList.remove('open');}
  startSketch(){const selected=store.project.selectedId;const plane=store.project.planes.find(p=>p.id===selected);if(!plane){this.toast('Select an XY, XZ, YZ, or custom reference plane first.','warning');this.q('#tree-panel')?.classList.add('open');return;}const sketch=createSketch(plane.id,`Sketch ${store.project.sketches.length+1}`);store.mutate('Create sketch',p=>{p.sketches.push(sketch);p.selectedId=sketch.id;});this.enterSketch(sketch.id);}
  enterSketch(id){const sketch=store.project.sketches.find(s=>s.id===id);if(!sketch)return;this.sketchEntrySnapshot=clone(store.project);store.project.activeSketchId=id;store.project.selectedId=id;this.mode='sketch';this.q('.workspace').dataset.mode='sketch';this.q('#mode-pill').textContent='SKETCH MODE';this.q('#sketch-overlay').classList.add('active');this.q('#command-bar').hidden=false;this.renderer.controls.enabled=false;this.sketchView.setSketch(sketch);this.activeTool='select';this.sketchController.setTool('select');this.setInstruction('select');this.refresh();}
  confirmCommand(){if(this.mode!=='sketch')return;const sketch=this.sketchController.sketch;solveSketch(sketch);detectProfiles(sketch);store.project.activeSketchId=null;this.mode='model';this.q('.workspace').dataset.mode='model';this.q('#mode-pill').textContent='3D MODEL';this.q('#sketch-overlay').classList.remove('active');this.q('#command-bar').hidden=true;this.renderer.controls.enabled=true;this.sketchEntrySnapshot=null;store.dirty=true;store.emit('change',{label:'Finish sketch'});this.renderer.rebuild();if(!sketch.profiles.some(p=>p.valid)&&sketch.entities.length)this.toast('Sketch saved, but it has no valid closed profile.','warning');}
  cancelCommand(){if(this.mode!=='sketch')return;if(this.sketchEntrySnapshot)store.setProject(this.sketchEntrySnapshot,{resetHistory:false});this.mode='model';this.q('.workspace').dataset.mode='model';this.q('#mode-pill').textContent='3D MODEL';this.q('#sketch-overlay').classList.remove('active');this.q('#command-bar').hidden=true;this.renderer.controls.enabled=true;this.renderer.setProject(store.project);this.refresh();}
  setInstruction(tool){const hints={select:'Tap geometry to select. Open Sketch again for tools.',line:'Tap two points.',polyline:'Tap points; double-tap to finish.',cornerRect:'Tap opposite corners.',centerRect:'Tap center, then corner.',circle:'Tap center, then radius.',centerArc:'Tap center, start, then end.',threeArc:'Tap start, through, then end.',polygon:'Tap center, then a vertex.',slot:'Tap the two centerline endpoints.',trim:'Tap a line or circle to trim.',extend:'Tap near a line endpoint.',offset:'Tap geometry to offset.',fillet:'Tap two connected lines.',construction:'Tap geometry to toggle construction.',project:'Tap to project the selected body bounds.',move:'Drag sketch geometry.',duplicate:'Tap geometry to duplicate.',delete:'Tap geometry to delete.'};const el=this.q('#command-instruction');if(el)el.textContent=hints[tool]||tool;}
  applyConstraint(type){const sketch=this.sketchController.sketch,ids=[...this.sketchView.selected];if(!sketch)return;const dimensional=['distanceX','distanceY','distance','radius','diameter','angle'].includes(type);if(dimensional){if(ids.length!==1){this.toast('Select exactly one sketch entity.','warning');return;}const entity=sketch.entities.find(e=>e.id===ids[0]),initial=inferredDimension(entity,type);this.valueDialog(`Set ${type}`,initial,value=>{store.mutate(`Add ${type} dimension`,p=>{const s=p.sketches.find(x=>x.id===p.activeSketchId);addDimension(s,type,ids[0],value);});this.sketchView.sketch=this.sketchController.sketch;this.sketchView.render();});}else{try{store.mutate(`Add ${type} constraint`,p=>addConstraint(p.sketches.find(x=>x.id===p.activeSketchId),type,ids));this.sketchView.sketch=this.sketchController.sketch;this.sketchView.render();this.closeSheet();}catch(e){this.toast(e.message,'error');}}
  }
  editDimension(id){const sketch=this.sketchController.sketch,dimension=sketch.dimensions.find(d=>d.id===id);if(!dimension)return;this.valueDialog(`Edit ${dimension.type}`,dimension.value,value=>{store.mutate('Edit dimension',p=>{const s=p.sketches.find(x=>x.id===p.activeSketchId),d=s.dimensions.find(x=>x.id===id);d.value=value;solveSketch(s);});this.sketchView.sketch=this.sketchController.sketch;this.sketchView.render();});}
  projectExternal(){const selected=this.lastBodyId||this.renderer.selected,object=selected&&this.renderer.findById(selected);if(!object){this.toast('Select a visible body before entering Sketch Mode, then use Project.','warning');return;}const box=new THREE.Box3().setFromObject(object),min=box.min,max=box.max;store.mutate('Project external geometry',p=>{const s=p.sketches.find(x=>x.id===p.activeSketchId);s.entities.push({id:uid('entity'),type:'rect',mode:'corner',a:{x:min.x,y:min.y},b:{x:max.x,y:max.y},construction:false,projected:true});solveSketch(s);});this.sketchView.sketch=this.sketchController.sketch;this.sketchView.render();}
  configureFeature(type){this.closeSheet();if(type==='referencePlane'){const selected=store.project.planes.find(p=>p.id===store.project.selectedId)||store.project.planes[0];this.featureDialog(type,{basePlaneId:selected.id});return;}const selectedId=store.project.selectedId,sketch=store.project.sketches.find(s=>s.id===selectedId),body=store.project.bodies.find(b=>b.id===selectedId);if(['extrude','cut','revolve','revolveCut'].includes(type)){const s=sketch||store.project.sketches.at(-1);if(!s){this.toast('Create and select a sketch first.','warning');return;}detectProfiles(s);if(!s.profiles.some(p=>p.valid)){this.toast('The sketch needs a valid closed profile.','error');return;}if(['cut','revolveCut'].includes(type)&&!store.project.bodies.length){this.toast('A cut needs an existing body.','warning');return;}this.featureDialog(type,{sketchId:s.id,bodyId:body?.id||store.project.bodies.at(-1)?.id});return;}if(type==='boolean'&&store.project.bodies.length<2){this.toast('Boolean needs two bodies.','warning');return;}const b=body||store.project.bodies.at(-1);if(!b&&type!=='boolean'){this.toast('Select or create a body first.','warning');return;}this.featureDialog(type,{bodyId:b?.id});}
  featureDialog(type,context){const project=store.project,bodyOptions=project.bodies.map(b=>`<option value="${b.id}" ${b.id===context.bodyId?'selected':''}>${escapeHTML(b.name)}</option>`).join('');let fields='';if(['extrude','cut'].includes(type))fields=this.num('depth',10,project.units)+this.check('symmetric','Symmetric',false);else if(['revolve','revolveCut'].includes(type))fields=this.num('angle',360,'°')+this.num('segments',48,'');else if(type==='fillet'||type==='chamfer')fields=this.num('amount',1,project.units);else if(type==='shell')fields=this.num('thickness',1,project.units);else if(type==='linearPattern')fields=this.select('axis',['x','y','z'])+this.num('count',3,'')+this.num('spacing',20,project.units);else if(type==='circularPattern')fields=this.select('axis',['x','y','z'])+this.num('count',4,'')+this.num('radius',30,project.units);else if(type==='mirror')fields=this.select('axis',['x','y','z']);else if(type==='referencePlane')fields=`<input type="hidden" name="basePlaneId" value="${context.basePlaneId}">${this.num('offset',10,project.units)+this.num('angle',0,'°')}`;else if(type==='boolean')fields=`<label>Body A<select name="bodyA">${bodyOptions}</select></label><label>Body B<select name="bodyB">${project.bodies.map((b,i)=>`<option value="${b.id}" ${i===1?'selected':''}>${escapeHTML(b.name)}</option>`).join('')}</select></label>${this.select('operation',['union','subtract','intersect'])}`;fields+=`<input type="hidden" name="type" value="${type}"><input type="hidden" name="sketchId" value="${context.sketchId||''}"><input type="hidden" name="bodyId" value="${context.bodyId||''}"><button class="primary full" type="submit">Create feature</button>`;this.openDialog(dialog(`Create ${type.replace(/([A-Z])/g,' $1')}`,`<form id="feature-form">${fields}</form>`));}
  createConfiguredFeature(data){const values=Object.fromEntries(data),type=values.type;if(type==='referencePlane'){commands.createReferencePlane(values.basePlaneId,Number(values.offset),Number(values.angle));this.closeDialog();this.renderer.updateReferences();return;}const sketch=store.project.sketches.find(s=>s.id===values.sketchId),profile=sketch?.profiles.find(p=>p.valid);const feature=createFeature(type,{sketchId:values.sketchId||null,profileId:profile?.id||null,bodyId:values.bodyId||null,params:{...values}});delete feature.params.type;delete feature.params.sketchId;delete feature.params.bodyId;for(const[k,v]of Object.entries(feature.params))if(v!==''&&Number.isFinite(Number(v)))feature.params[k]=Number(v);feature.params.symmetric=data.has('symmetric');if(['cut','revolveCut','fillet','chamfer','shell','linearPattern','circularPattern','mirror'].includes(type))feature.outputBodyId=feature.bodyId;if(type==='boolean'){feature.outputBodyId=values.bodyA;feature.bodyId=values.bodyA;}store.mutate(`Create ${type}`,p=>{p.features.push(feature);p.selectedId=feature.id;});this.closeDialog();this.renderer.rebuild();}
  async save(silent=false){if(!store.project)return;try{const saved=await projectDB.save(store.project);store.project.updatedAt=saved.updatedAt;store.markSaved();await projectDB.recovery.delete(store.project.id).catch(()=>{});this.refresh();if(!silent)this.toast('Project saved locally.');}catch(e){this.toast(`Save failed: ${e.message}`,'error');}}
  saveAs(){this.renameDialog('Save As',`${store.project.name} Copy`,async name=>{const copy=clone(store.project);copy.id=uid('project');copy.name=name;store.setProject(copy);await this.save();this.refresh();});}
  renameProject(){this.renameDialog('Rename Project',store.project.name,name=>commands.rename(store.project.id,name));}
  async duplicateProject(){const copy=await projectDB.duplicate(store.project);this.toast(`Created ${copy.name}.`);}
  deleteProject(){this.confirm('Delete project?',`Delete “${store.project.name}” from this browser? This cannot be undone.`,async()=>{await projectDB.delete(store.project.id);await this.showWelcome();});}
  deleteSelected(){const id=store.project.selectedId,item=store.project.features.find(x=>x.id===id)||store.project.sketches.find(x=>x.id===id)||store.project.bodies.find(x=>x.id===id)||store.project.planes.find(x=>x.id===id);if(!item||item.standard)return;this.confirm('Delete item?',`Delete “${item.name}” and directly dependent history?`,()=>{commands.remove(id);this.renderer.rebuild();});}
  moveFeature(direction){const id=store.project.selectedId,planBefore=JSON.stringify(planRebuild(store.project));commands.reorderFeature(id,direction);const invalid=planRebuild(store.project).some(s=>s.error);if(invalid){store.undo();this.toast('That reorder would break feature dependencies.','error');}else this.renderer.rebuild();}
  async openProjectPicker(){const projects=await projectDB.list();if(!projects.length){this.toast('No saved projects yet.');return;}this.openSheet(sheet('Open Project',`<div class="menu-list">${projects.map(p=>`<button data-action="load-project" data-id="${p.id}"><span class="project-list-icon">FC</span><span><strong>${escapeHTML(p.name)}</strong><small>${p.units.toUpperCase()} · ${new Date(p.updatedAt).toLocaleString()}</small></span></button>`).join('')}</div>`));}
  async loadProject(id){const project=await projectDB.get(id);if(!project){this.toast('Project was not found.','error');return;}const recovery=await projectDB.recovery.get(id).catch(()=>null);if(recovery&&new Date(recovery.savedAt)>new Date(project.updatedAt)){this.confirm('Recovery snapshot found','Restore the newer local crash-recovery snapshot?',()=>this.openWorkspace(recovery.project),()=>this.openWorkspace(project));}else this.openWorkspace(project);}
  async importFile(file){if(!file)return;document.getElementById('file-picker').value='';this.progress(0);try{const result=await importer.import(file);this.progress(null);if(result.kind==='native'){await this.openWorkspace(result.project);this.toast('Native project opened with editable history.');return;}let project=store.project;if(!project){project=createProject({name:fileBase(file.name),units:'mm',template:'blank'});store.setProject(project);}if(result.kind==='mesh'){store.mutate('Import mesh',p=>{p.imports.push(result);p.selectedId=result.bodyId;});}else if(result.kind==='sketch'){const sketch=createSketch('plane-xy',`Imported ${fileBase(file.name)}`);sketch.entities=result.entities;sketch.imported=true;sketch.warnings=result.warnings;detectProfiles(sketch);store.mutate('Import sketch',p=>{p.sketches.push(sketch);p.imports.push({...result,id:uid('import'),name:file.name,sketchId:sketch.id});p.selectedId=sketch.id;});}if(this.mode==='welcome')await this.openWorkspace(store.project);else{this.renderer.setProject(store.project);this.refresh();}this.toast((result.warnings||['Import complete.'])[0],'warning');}catch(e){this.progress(null);this.toast(e.message,'error');}}
  measure(){const body=store.project.bodies.find(b=>b.id===store.project.selectedId)||store.project.bodies[0];if(!body?.metrics){this.toast('Select a built or imported body to measure.','warning');return;}const m=body.metrics,unit=store.project.units;this.openSheet(sheet('Measure',`<div class="metrics large"><div><span>Bounding box</span><strong>${m.bounds.map(v=>v.toFixed(3)).join(' × ')} ${unit}</strong></div><div><span>Face area (all mesh faces)</span><strong>${m.area.toFixed(3)} ${unit}²</strong></div><div><span>Body volume</span><strong>${m.volume.toFixed(3)} ${unit}³</strong></div><div><span>Bounding diagonal</span><strong>${Math.hypot(...m.bounds).toFixed(3)} ${unit}</strong></div></div><label>Material density (mass/${unit}³)<input id="measure-density" type="number" inputmode="decimal" value="${body.density||0}" step="any"></label><button class="secondary full" data-action="apply-density">Calculate approximate mass</button><p class="field-help">Distances, areas, and volume are calculated from the rendered triangle mesh.</p>`));const button=this.q('[data-action="apply-density"]');button.onclick=()=>{const density=Number(this.q('#measure-density').value)||0;store.mutate('Set material density',p=>p.bodies.find(b=>b.id===body.id).density=density);this.toast(`Approximate mass: ${(m.volume*density).toFixed(4)}`);};}
  valueDialog(title,value,handler){this.confirmHandler=handler;this.openDialog(dialog(title,`<form id="value-form"><label>Value<input name="value" type="number" inputmode="decimal" step="any" value="${value}" autofocus required></label><div class="dialog-actions"><button type="button" class="secondary" data-action="close-dialog">Cancel</button><button class="primary" type="submit">Apply</button></div></form>`));}
  renameDialog(title,value,handler){this.confirmHandler=handler;this.openDialog(dialog(title,`<form id="rename-form"><label>Name<input name="name" value="${escapeHTML(value)}" required maxlength="80" autofocus></label><div class="dialog-actions"><button type="button" class="secondary" data-action="close-dialog">Cancel</button><button class="primary" type="submit">Apply</button></div></form>`));}
  confirm(title,message,yes,no=null){this.confirmHandler=yes;this.cancelHandler=no;this.openDialog(dialog(title,`<p>${escapeHTML(message)}</p><div class="dialog-actions"><button class="secondary" data-action="confirm-no">Cancel</button><button class="danger" data-action="confirm-yes">Confirm</button></div>`));this.q('[data-action="confirm-yes"]').onclick=()=>{const fn=this.confirmHandler;this.closeDialog();fn?.();};this.q('[data-action="confirm-no"]').onclick=()=>{const fn=this.cancelHandler;this.closeDialog();fn?.();};}
  goHome(){if(store.dirty)this.save(true);this.showWelcome();}
  toggleTheme(){const current=document.documentElement.dataset.theme,next=current==='dark'?'light':'dark';localStorage.setItem('feathercad-theme',next);this.applyTheme(next);}
  applyTheme(theme){if(theme==='system')theme=matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';document.documentElement.dataset.theme=theme;}
  openSheet(html){let layer=this.q('#sheet-layer');if(!layer){layer=document.createElement('div');layer.id='sheet-layer';this.root.appendChild(layer);}layer.innerHTML=html;}
  closeSheet(){const layer=this.q('#sheet-layer');if(layer)layer.innerHTML='';}
  openDialog(html){const layer=this.q('#dialog-layer')||this.ensureDialogLayer();layer.innerHTML=html;setTimeout(()=>layer.querySelector('[autofocus]')?.focus(),20);}
  closeDialog(){const layer=this.q('#dialog-layer');if(layer)layer.innerHTML='';this.confirmHandler=null;this.cancelHandler=null;}
  ensureDialogLayer(){let layer=this.q('#dialog-layer');if(!layer){layer=document.createElement('div');layer.id='dialog-layer';this.root.appendChild(layer);}return layer;}
  progress(value){const el=this.q('#operation-progress');if(!el)return;el.hidden=value==null;el.querySelector('span').style.width=`${Math.round((value||0)*100)}%`;}
  toast(message,type='info'){const region=document.getElementById('toast-region'),node=document.createElement('div');node.className=`toast ${type}`;node.textContent=message;region.appendChild(node);setTimeout(()=>node.remove(),4200);}
  attachLongPress(){let timer,start;const canvas=this.q('#viewport');canvas.addEventListener('pointerdown',e=>{start={x:e.clientX,y:e.clientY};timer=setTimeout(()=>{navigator.vibrate?.(15);this.openSheet(sheet('Context actions',`<div class="menu-list"><button data-action="fit">Focus / fit selection</button><button data-action="measure">Measure body</button><button data-action="feature-menu">Add feature</button><button data-action="delete-item" class="danger">Delete selected item</button></div>`));},600);});canvas.addEventListener('pointermove',e=>{if(start&&Math.hypot(e.clientX-start.x,e.clientY-start.y)>10)clearTimeout(timer);});for(const event of ['pointerup','pointercancel'])canvas.addEventListener(event,()=>clearTimeout(timer));}
  num(name,value,unit){return`<label>${name.replace(/^./,c=>c.toUpperCase())}<div class="unit-input"><input type="number" inputmode="decimal" step="any" name="${name}" value="${value}" required><span>${unit}</span></div></label>`;}
  check(name,label,checked){return`<label class="switch"><input type="checkbox" name="${name}" ${checked?'checked':''}><span>${label}</span></label>`;}
  select(name,values){return`<label>${name.replace(/^./,c=>c.toUpperCase())}<select name="${name}">${values.map(v=>`<option value="${v}">${v}</option>`).join('')}</select></label>`;}
  q(selector){return this.root.querySelector(selector);}
}

new FeatherCADApp(document.getElementById('app'));
