import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { COLORS } from './constants.js';
import { applyBodyFeature, metricsForObject } from './geometry/features.js';
import { planRebuild, syncBodies } from './history.js';

export class CADRenderer extends EventTarget {
  constructor(container,canvas){
    super();this.container=container;this.canvas=canvas;this.project=null;this.displayMode='edges';this.selectionFilter='body';this.selected=null;this.needsRender=true;
    this.renderer=new THREE.WebGLRenderer({canvas,antialias:matchMedia('(min-resolution: 2dppx)').matches?false:true,alpha:false,powerPreference:'high-performance',preserveDrawingBuffer:true});
    this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.setClearColor(0xf3f7f9);this.renderer.localClippingEnabled=true;
    this.scene=new THREE.Scene();this.scene.fog=new THREE.Fog(0xf3f7f9,500,1200);this.perspective=new THREE.PerspectiveCamera(45,1,.1,5000);this.orthographic=new THREE.OrthographicCamera(-100,100,100,-100,.1,5000);this.camera=this.perspective;
    this.controls=new OrbitControls(this.camera,canvas);this.controls.enableDamping=true;this.controls.dampingFactor=.08;this.controls.screenSpacePanning=true;this.controls.touches.ONE=THREE.TOUCH.ROTATE;this.controls.touches.TWO=THREE.TOUCH.DOLLY_PAN;this.controls.addEventListener('change',()=>{this.invalidate();this.saveCamera();});
    this.modelGroup=new THREE.Group();this.modelGroup.name='Bodies';this.referenceGroup=new THREE.Group();this.referenceGroup.name='References';this.scene.add(this.modelGroup,this.referenceGroup);
    this.scene.add(new THREE.HemisphereLight(0xffffff,0x6c8790,2.2));const key=new THREE.DirectionalLight(0xffffff,2.5);key.position.set(120,180,90);this.scene.add(key);const fill=new THREE.DirectionalLight(0x80c9e8,1);fill.position.set(-90,40,-100);this.scene.add(fill);
    this.grid=new THREE.GridHelper(400,40,0x7b8e96,0xc7d3d8);this.grid.material.opacity=.45;this.grid.material.transparent=true;this.scene.add(this.grid);this.axes=new THREE.AxesHelper(35);this.scene.add(this.axes);this.origin=new THREE.Mesh(new THREE.SphereGeometry(1.4,16,8),new THREE.MeshBasicMaterial({color:0xffb000}));this.origin.userData={id:'origin',kind:'origin'};this.scene.add(this.origin);
    this.raycaster=new THREE.Raycaster();this.pointer=new THREE.Vector2();this.canvas.addEventListener('pointerup',e=>this.pick(e));this.canvas.addEventListener('pointermove',e=>this.preselect(e));this.canvas.addEventListener('dblclick',()=>this.fit(this.selected));
    this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(container);this.setView('iso');this.loop();
  }
  setProject(project){this.project=project;if(project?.camera){this.camera.position.fromArray(project.camera.position);this.controls.target.fromArray(project.camera.target);}this.rebuild();this.updateReferences();}
  async rebuild(){
    this.disposeGroup(this.modelGroup);this.modelGroup=new THREE.Group();this.scene.add(this.modelGroup);if(!this.project)return;
    const plan=planRebuild(this.project),bodies=new Map();
    for(const imported of this.project.imports){if(!imported.meshData||!imported.bodyId)continue;try{const mesh=this.meshFromData(imported.meshData);mesh.userData={id:imported.bodyId,kind:'body',importId:imported.id};bodies.set(imported.bodyId,mesh);}catch(error){imported.error=error.message;}}
    for(const step of plan){const feature=this.project.features.find(f=>f.id===step.featureId);feature.error=step.error;feature.status=feature.suppressed?'suppressed':step.error?'error':'rebuilding';if(step.error||feature.suppressed)continue;try{const outputs=applyBodyFeature(feature,this.project,bodies);for(const output of outputs){output.mesh.userData={id:output.id,kind:'body',featureId:feature.id};bodies.set(output.id,output.mesh);if(feature.bodyId&&output.id===feature.bodyId)bodies.set(feature.bodyId,output.mesh);}feature.status='ok';feature.lastValid={revision:this.project.revision};}catch(error){feature.status='error';feature.error=error.message;}}
    syncBodies(this.project);const liveIds=new Set(this.project.bodies.map(body=>body.id));
    for(const [id,object] of bodies){if(!liveIds.has(id))continue;const body=this.project.bodies.find(b=>b.id===id);object.visible=body?.visible??true;object.userData.id=id;this.applyDisplay(object);this.modelGroup.add(object);if(body)body.metrics=metricsForObject(object);}
    this.invalidate();this.dispatchEvent(new CustomEvent('rebuilt',{detail:{plan}}));
  }
  meshFromData(data){const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(data.positions,3));if(data.indices?.length)geometry.setIndex(data.indices);if(data.normals?.length)geometry.setAttribute('normal',new THREE.Float32BufferAttribute(data.normals,3));else geometry.computeVertexNormals();geometry.computeBoundingBox();return new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({color:COLORS.body,roughness:.6,metalness:.02,side:THREE.DoubleSide}));}
  updateReferences(){this.disposeGroup(this.referenceGroup);this.referenceGroup=new THREE.Group();this.scene.add(this.referenceGroup);if(!this.project)return;for(const plane of this.project.planes){const geometry=new THREE.PlaneGeometry(100,100),material=new THREE.MeshBasicMaterial({color:plane.color||0x35a7d0,transparent:true,opacity:.07,side:THREE.DoubleSide,depthWrite:false});const mesh=new THREE.Mesh(geometry,material);mesh.userData={id:plane.id,kind:'plane'};mesh.visible=this.project.visibility.planes&&plane.visible;if(plane.id==='plane-xz')mesh.rotation.x=Math.PI/2;else if(plane.id==='plane-yz')mesh.rotation.y=Math.PI/2;else if(!plane.standard){const base=this.project.planes.find(p=>p.id===plane.basePlaneId);if(base?.id==='plane-xz')mesh.rotation.x=Math.PI/2;if(base?.id==='plane-yz')mesh.rotation.y=Math.PI/2;mesh.position.z=plane.offset||0;mesh.rotation.z=THREE.MathUtils.degToRad(plane.angle||0);}const edges=new THREE.LineSegments(new THREE.EdgesGeometry(geometry),new THREE.LineBasicMaterial({color:plane.color||0x35a7d0,transparent:true,opacity:.4}));mesh.add(edges);this.referenceGroup.add(mesh);}this.grid.visible=this.project.visibility.grid;this.axes.visible=this.project.visibility.axes;this.origin.visible=this.project.visibility.origin;this.invalidate();}
  applyDisplay(object){object.traverse(child=>{if(!child.isMesh)return;const color=child.material?.color?.getHex()||COLORS.body;child.material=new THREE.MeshStandardMaterial({color,roughness:.55,metalness:.05,transparent:this.displayMode==='transparent',opacity:this.displayMode==='transparent'?.35:1,wireframe:this.displayMode==='wireframe',side:THREE.DoubleSide,clippingPlanes:this.sectionEnabled?[this.sectionPlane]:[]});const old=child.getObjectByName('edge-overlay');if(old)child.remove(old);if(this.displayMode==='edges'){const edge=new THREE.LineSegments(new THREE.EdgesGeometry(child.geometry,28),new THREE.LineBasicMaterial({color:COLORS.edge}));edge.name='edge-overlay';child.add(edge);}});}
  setDisplay(mode){this.displayMode=mode;for(const object of this.modelGroup.children)this.applyDisplay(object);this.invalidate();}
  setProjection(type){const old=this.camera;const target=this.controls.target.clone();this.camera=type==='orthographic'?this.orthographic:this.perspective;this.camera.position.copy(old.position);this.camera.up.copy(old.up);this.controls.object=this.camera;this.controls.target.copy(target);this.resize();if(this.project)this.project.camera.projection=type;}
  setView(view){const dirs={front:[0,0,1],back:[0,0,-1],left:[-1,0,0],right:[1,0,0],top:[0,1,0],bottom:[0,-1,0],iso:[1,1,1]};const d=new THREE.Vector3(...(dirs[view]||dirs.iso)).normalize(),distance=this.camera.position.distanceTo(this.controls.target)||220;this.camera.position.copy(this.controls.target).addScaledVector(d,distance);this.camera.up.set(0,view==='top'||view==='bottom'?0:1,view==='top'?-1:view==='bottom'?1:0);this.controls.update();this.invalidate();}
  fit(id=null){const object=id?this.findById(id):this.modelGroup;if(!object||!this.modelGroup.children.length&&!id){this.controls.target.set(0,0,0);this.camera.position.set(140,110,140);this.controls.update();return;}const box=new THREE.Box3().setFromObject(object);if(box.isEmpty())return;const center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()).length()||50;const dir=this.camera.position.clone().sub(this.controls.target).normalize();this.controls.target.copy(center);this.camera.position.copy(center).addScaledVector(dir,size*1.6);if(this.camera.isOrthographic){this.camera.zoom=Math.max(.1,200/size);this.camera.updateProjectionMatrix();}this.controls.update();this.invalidate();}
  toggleSection(enabled){this.sectionEnabled=enabled;this.sectionPlane=this.sectionPlane||new THREE.Plane(new THREE.Vector3(1,0,0),0);for(const o of this.modelGroup.children)this.applyDisplay(o);this.invalidate();}
  setSelectionFilter(filter){this.selectionFilter=filter;}
  pick(event){if(event.pointerType==='touch'&&Math.hypot(event.movementX||0,event.movementY||0)>4)return;const hits=this.intersections(event);const hit=hits.find(x=>this.matchesFilter(x.object));this.select(hit?.object||null);}
  preselect(event){if(event.pointerType==='touch')return;const hit=this.intersections(event).find(x=>this.matchesFilter(x.object));this.canvas.style.cursor=hit?'pointer':'grab';}
  intersections(event){const r=this.canvas.getBoundingClientRect();this.pointer.set((event.clientX-r.left)/r.width*2-1,-(event.clientY-r.top)/r.height*2+1);this.raycaster.setFromCamera(this.pointer,this.camera);return this.raycaster.intersectObjects([this.modelGroup,this.referenceGroup,this.origin],true);}
  matchesFilter(object){const root=this.rootDataObject(object);if(!root)return false;return this.selectionFilter==='feature'?!!root.userData.featureId:this.selectionFilter==='body'?root.userData.kind==='body':true;}
  rootDataObject(object){let current=object;while(current&&!current.userData?.id)current=current.parent;return current;}
  select(object){if(this.selected){const old=this.findById(this.selected);old?.traverse(c=>{if(c.isMesh&&c.material?.emissive)c.material.emissive.setHex(0)});}const root=this.rootDataObject(object);this.selected=root?.userData.id||null;if(root)root.traverse(c=>{if(c.isMesh&&c.material?.emissive)c.material.emissive.setHex(0x5c3500)});this.invalidate();this.dispatchEvent(new CustomEvent('selection',{detail:{id:this.selected,featureId:root?.userData.featureId||null,point:null}}));}
  findById(id){let found=null;this.scene.traverse(o=>{if(o.userData?.id===id)found=o});return found;}
  setVisibility(id,visible){const object=this.findById(id);if(object)object.visible=visible;this.invalidate();}
  snapshot(){this.render();return new Promise(resolve=>this.canvas.toBlob(resolve,'image/png'));}
  saveCamera(){if(!this.project)return;this.project.camera={projection:this.camera.isOrthographic?'orthographic':'perspective',position:this.camera.position.toArray(),target:this.controls.target.toArray(),up:this.camera.up.toArray()};}
  resize(){const w=Math.max(1,this.container.clientWidth),h=Math.max(1,this.container.clientHeight);this.renderer.setSize(w,h,false);this.perspective.aspect=w/h;this.perspective.updateProjectionMatrix();const span=100,aspect=w/h;this.orthographic.left=-span*aspect;this.orthographic.right=span*aspect;this.orthographic.top=span;this.orthographic.bottom=-span;this.orthographic.updateProjectionMatrix();this.invalidate();}
  invalidate(){this.needsRender=true;}
  render(){this.renderer.render(this.scene,this.camera);this.needsRender=false;}
  loop(){if(this.destroyed)return;this.frame=requestAnimationFrame(()=>this.loop());if(this.controls.update()||this.needsRender)this.render();}
  destroy(){this.destroyed=true;cancelAnimationFrame(this.frame);this.resizeObserver.disconnect();this.controls.dispose();this.disposeGroup(this.modelGroup);this.disposeGroup(this.referenceGroup);this.renderer.dispose();}
  disposeGroup(group){if(!group)return;group.traverse(object=>{object.geometry?.dispose();if(Array.isArray(object.material))object.material.forEach(m=>m.dispose());else object.material?.dispose();});this.scene.remove(group);}
}
